### ISSUE TITLE
[finish] joint consensus for Raft

### ISSUE THREAD

**Issue by JayiceZ** [JayiceZ/awesome-reading#4]

**Comment by jiekun** [comment]
any update?

**Comment by JayiceZ** [comment]
> any update?

Thanks for your attention. 
I manage a reading-list-series on my website https://jayicez.github.io/posts/2024-06-blog/. And i will update it every few days

**Comment by JayiceZ** [comment]
> any update?

BTW, i am a super knower in raft now, and no updates needed
